# Generated by Django 2.1.2 on 2018-10-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title_id',
            field=models.UUIDField(),
        ),
    ]
