# Generated by Django 2.1.2 on 2018-10-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181031_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title_id',
            field=models.CharField(max_length=50),
        ),
    ]
